//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SellFootWear.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin
    {
        public int IDAmin { get; set; }
        public string NameAdmin { get; set; }
        public string AddressAdmin { get; set; }
        public string PhoneAdmin { get; set; }
        public string UserAdmin { get; set; }
        public string Password { get; set; }
        public Nullable<bool> GenderAdmin { get; set; }
        public string EmailAdmin { get; set; }
    }
}
