//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SellFootWear.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
        }
    
        public int pID { get; set; }
        public string NameProduct { get; set; }
        public string image { get; set; }
        public string image2 { get; set; }
        public string image3 { get; set; }
        public Nullable<int> TypeID { get; set; }
        public Nullable<decimal> price { get; set; }
        public string describeshort { get; set; }
        public string describe { get; set; }
        public Nullable<int> BrandID { get; set; }
        public Nullable<System.DateTime> UpdateDay { get; set; }
        public Nullable<bool> Discount { get; set; }
        public Nullable<decimal> pricediscount { get; set; }
    
        public virtual Brand Brand { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        public virtual Type Type { get; set; }
    }
}
